import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'

import { cn } from '@/lib/utils'

import './globals.css'

import { ThemeProvider } from '@/components/providers/theme-provider'
import ProgressBar from '@/components/base/progress-bar'
import NavigationBar from '@/components/base/navigation-bar'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
})

export const metadata: Metadata = {
  title: {
    template: '%s | sugarblog',
    default: 'sugarblog'
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(
        'min-h-screen bg-background font-sans antialiased',
        fontSans.variable,
      )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          storageKey="color-theme"
        >
          <ProgressBar />
          <nav className='sticky top-0 md:py-2 bg-background z-50'>
            <NavigationBar />
          </nav>
          <main className='max-w-[768px] m-auto'>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
